const ingredients = [
  { name: "Milk", description: "Your choice of dairy or plant-based" },
  {
    name: "Peanut Butter",
    description: "Can also be subbed out for your favorite nut or seed butter",
  },
  { name: "Coconut Oil", description: "" },
  { name: "Brown Sugar", description: "Light or dark is fine" },
  { name: "Vanilla Extract", description: "" },
  { name: "Baking Soda", description: "" },
  {
    name: "Kosher Salt",
    description:
      "If subbing for table salt, check salt conversion measurements",
  },
  {
    name: "Table Salt",
    description:
      "If subbing for kosher salt, check salt conversion measurements",
  },
  { name: "Coconut Flour", description: "Can be subbed for plain flour" },
  { name: "Confectioners Sugar", description: "" },
  { name: "Powdered Sugar", description: "" },
  { name: "Light Corn Syrup", description: "" },
  { name: "Cocoa Powder", description: "" },
  { name: "Tequila", description: "Alcohol" },
  { name: "Lime Juice", description: "" },
  { name: "Triple Sec", description: "Alcohol" },
  { name: "Beet Juice", description: "" },
  { name: "Cayenne Powder", description: "" },
  { name: "Lime", description: "" },
  { name: "Rice Vineggar", description: "" },
  { name: "Shaoxing Wine", description: "" },
  { name: "Soy Sauce", description: "" },
  { name: "Hoisin Sauce", description: "" },
  { name: "Oyster Sauce", description: "" },
  { name: "Garlic", description: "" },
  { name: "Ginger", description: "" },
  { name: "Chili Oil", description: "" },
  { name: "Chicken Wings", description: "" },
  { name: "Five Spice Powder", description: "" },
  { name: "Scallion", description: "Green onions" },
  { name: "Bell Pepper", description: "Any color is fine" },
  { name: "Habanero Pepper", description: "" },
  { name: "Cumin", description: "" },
  { name: "Honey", description: "Local is best" },
  { name: "Cilantro", description: "Can be subbed with parsley" },
  { name: "Canola Oil", description: "" },
  { name: "Orange Juice", description: "" },
  { name: "Curry Powder", description: "" },
  { name: "Allspice", description: "" },
  { name: "Large Shrimp", description: "" },
  { name: "Ramen", description: "" },
  { name: "Egg(s)", description: "" },
  { name: "Pork Belly", description: "" },
  { name: "Cinnamon", description: "" },
  { name: "Thick Cut Bacon", description: "" },
  { name: "Bread", description: "" },
  { name: "Cheddar", description: "" },
  { name: "Water", description: "" },
  {
    name: "Loose Leaf Hibiscus Tea",
    description: "Can be subbed for 1 tea bag",
  },
  { name: "Japanese Whiskey", description: "" },
  { name: "Granulated Sugar", description: "" },
  {
    name: "Cake Flour",
    description: "Not to be confused with self-rising or bread flour",
  },
  { name: "Cream of Tartar", description: "" },
  { name: "Heavy Whipping Cream", description: "" },
  { name: "Chili Powder", description: "" },
  { name: "Cornstarch", description: "" },
  { name: "Matcha", description: "Green tea powder" },

  // {"name":"",
  // "description":""
  // },
];
module.exports = { ingredients };
